apiVersion: v1
kind: ConfigMap
metadata:
  name: RELEASE-NAME-lnd
  labels:
    app: lnd
    chart: lnd-1.0.0
    release: RELEASE-NAME
    heritage: Helm
data:
  lnf.conf: |-
    [Application Options]
    maxpendingchannels=5
    [autopilot]
    autopilot.active=0
    autopilot.maxchannels=5
