apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lnd.fullname" . }}
  labels:
    {{- include "lnd.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "lnd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "lnd.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "lnd.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: DEBUG
              value: {{ .Values.lnd.debug }}
            - name: NETWORK
              value: {{ .Values.lnd.network }}
            - name: LIGHTNING_DATA
              value: {{ .Values.lnd.dataDir }}
            - name: CHAIN
              value: {{ .Values.lnd.chain }}
            - name: BACKEND
              value: {{ .Values.lnd.backend }}
            - name: ZMQ_PUB_RAW_TX
              value: {{ .Values.bitcoin.zmqPubRawTx }}
            - name: ZMQ_PUB_RAW_BLK
              value: {{ .Values.bitcoin.zmqPubRawBlk }}
            - name: BITCOIN_RPC_HOST
              value: {{ .Values.bitcoin.host }}
            - name: BITCOIN_RPC_USER
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: bitcoin.user
            - name: BITCOIN_RPC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: bitcoin.password
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: config
              mountPath: /data/.lnd/lnd.conf
            - name: data
              mountPath: /data/.lnd
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          emptyDir: {}
        - name: configmap
          configMap:
            name: RELEASE-NAME-lightning
        - name: data
          persistentVolumeClaim:
          claimName: RELEASE-NAME-lightning
