apiVersion: v1
kind: Service
metadata:
  name: {{ include "lnd.fullname" . }}
  labels:
    {{- include "lnd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.rpc.port }}
      targetPort: rpc
      protocol: TCP
      name: rpc
    - port: {{ .Values.service.p2p.port }}
      targetPort: p2p
      protocol: TCP
      name: p2p
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "lnd.selectorLabels" . | nindent 4 }}
